# Generated by Django 5.1.7 on 2025-03-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('ddd', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_eletronico', models.CharField(blank=True, max_length=255, null=True)),
                ('representante', models.CharField(max_length=255)),
                ('cargo_representante', models.CharField(max_length=100)),
                ('data_registro_ans', models.DateField()),
            ],
        ),
    ]
